PROMPT Creating Table 'STUDENT_COURSE_SUSPENSION'
CREATE TABLE STUDENT_COURSE_SUSPENSION
 (STUDENT_ID NUMBER(8,0) 
 ,SECTION_ID NUMBER(8,0) 
 ,SUSPENSION_PERIOD_IN_YEARS NUMBER(1,0)
 ,START_DATE DATE 
 ,END_DATE DATE
 ,CREATED_BY VARCHAR2(30) 
 ,CREATED_DTM DATE
 )
/

PROMPT Creating Table 'ENROLLMENT_LOG'
CREATE TABLE ENROLLMENT_LOG
 (
 TRANSACTION_DTM DATE
 ,TRANSACTION_OWNER VARCHAR(30)
 ,ACTION_PERFORMED VARCHAR(30)
 ,STUDENT_ID NUMBER(8,0) 
 ,OLD_SECTION_ID NUMBER(8,0) 
 ,OLD_ENROLL_DATE DATE 
 ,OLD_FINAL_GRADE NUMBER(3,0)
 ,OLD_CREATED_BY VARCHAR2(30) 
 ,OLD_CREATED_DATE DATE
 ,OLD_MODIFIED_BY VARCHAR2(30) 
 ,OLD_MODIFIED_DATE DATE 
 ,NEW_SECTION_ID NUMBER(8,0)
 )
/

PROMPT Creating Table 'STUDENT_LOG'
CREATE TABLE STUDENT_LOG
 (
 TRANSACTION_DTM DATE
 ,TRANSACTION_OWNER VARCHAR(30)
 ,ACTION_PERFORMED VARCHAR(30)
 ,STUDENT_ID NUMBER(8,0) 
 ,OLD_SALUTATION VARCHAR2(5)
 ,OLD_FIRST_NAME VARCHAR2(25)
 ,OLD_LAST_NAME VARCHAR2(25) 
 ,OLD_STREET_ADDRESS VARCHAR2(50)
 ,OLD_ZIP VARCHAR2(5) 
 ,OLD_PHONE VARCHAR2(15)
 ,OLD_EMPLOYER VARCHAR2(50)
 ,OLD_REGISTRATION_DATE DATE 
 ,OLD_CREATED_BY VARCHAR2(30) 
 ,OLD_CREATED_DATE DATE 
 ,OLD_MODIFIED_BY VARCHAR2(30) 
 ,OLD_MODIFIED_DATE DATE
 )
/

PROMPT Creating Table 'student_final_mark'
CREATE TABLE student_final_mark
 (STUDENT_ID      NUMBER(8)    
,SALUTATION      VARCHAR2(5)  
,FIRST_NAME      VARCHAR2(25) 
,LAST_NAME       VARCHAR2(25) 
,PHONE           VARCHAR2(15) 
,SECTION_ID      NUMBER(8)    
,START_DATE_TIME DATE         
,INSTRUCTOR_ID   NUMBER(8)    
,COURSE_NO       NUMBER(8)    
,DESCRIPTION     VARCHAR2(50) 
,FINAL_MARKS     NUMBER  
 )
/

